AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AccountDailyBalanceTableName:
    Description: The name of the account daily balance table
    Type: String
  AccountMonthlyBalanceTableName:
    Description: The name of the account montly balance table
    Type: String
  AccountTransactionsTableName:
    Description: The name of the account transactions table
    Type: String
  LastTransactionDateTableName:
    Description: The name of the last-transaction date table
    Type: String
Resources:
  AccountDailyBalanceTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: DateSec
        AttributeType: N
      - AttributeName: BankName
        AttributeType: S
      KeySchema:
      - AttributeName: DateSec
        KeyType: HASH
      - AttributeName: BankName
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Ref: AccountDailyBalanceTableName
    Type: AWS::DynamoDB::Table
  AccountTransactionsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: TransactionDateSec
        AttributeType: N
      - AttributeName: UUID
        AttributeType: S
      KeySchema:
      - AttributeName: TransactionDateSec
        KeyType: HASH
      - AttributeName: UUID
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      TableName:
        Ref: AccountTransactionsTableName
    Type: AWS::DynamoDB::Table
  DailyBalanceStreamProcessor:
    Properties:
      CodeUri: s3://project-erebor-deployment-bucket/5cb28608ad718b3840dde6236a795eff
      Environment:
        Variables:
          ACCOUNT_DAILY_BALANCE_TABLE: AccountDailyBalanceTableName
          ACCOUNT_MONTHLY_BALANCE_TABLE: AccountMonthlyBalanceTableName
      Events:
        Stream:
          Properties:
            BatchSize: 10
            StartingPosition: TRIM_HORIZON
            Stream:
              Fn::GetAtt:
              - AccountTransactionsTable
              - StreamArn
          Type: DynamoDB
      Handler: balance.updateDailyBalance
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  LastTransactionDateTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: BankName
        AttributeType: S
      - AttributeName: SequenceNumber
        AttributeType: N
      KeySchema:
      - AttributeName: BankName
        KeyType: HASH
      - AttributeName: SequenceNumber
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName:
        Ref: LastTransactionDateTableName
    Type: AWS::DynamoDB::Table
  ListAllTransactionsFunction:
    Properties:
      CodeUri: s3://project-erebor-deployment-bucket/5cb28608ad718b3840dde6236a795eff
      Environment:
        Variables:
          ACCOUNT_TRANSACTIONS_TABLE_NAME: AccountTransactionsTableName
      Events:
        ListAllTransactions:
          Properties:
            Method: get
            Path: /transactions
          Type: Api
      Handler: transactions.list
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  ListDateRangeFunction:
    Properties:
      CodeUri: s3://project-erebor-deployment-bucket/5cb28608ad718b3840dde6236a795eff
      Environment:
        Variables:
          ACCOUNT_TRANSACTIONS_TABLE_NAME: AccountTransactionsTableName
      Events:
        ListDateRange:
          Properties:
            Method: get
            Path: /transactions/{startDateSecStr}/{endDateSecStr}
          Type: Api
      Handler: transactions.listBetweenDates
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
